### ISSUE TITLE
Grammar does not reflect prose concerning common attributes

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-grammar#22]
The specs says "Attributes from the XML namespace are allowed anywhere." but to my reading only xml:id and xml:base are allowed.
Someone with an expertise in Relax NG should fix this problem.

**Comment by ndw** [comment]
Righto. Because of attribute type reasons, I'm going to enumerate them instead of making a generic xml:* pattern.

I can think of `xml:id`, `xml:base`, `xml:lang`, and `xml:space`. Have I missed any?
